//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Networks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Networks.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Join a Network&lt;/h3&gt;
        ///&lt;p&gt;To join this network you need to confirm your e-mail address for that network. Enter your e-mail address below:&lt;/p&gt;
        ///&lt;form action=&quot;{S_FORM_ACTION}&quot; method=&quot;post&quot;&gt;
        ///&lt;fieldset&gt;
        ///		&lt;legend&gt;Join a Network&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;email&quot;&gt;E-mail:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;email&quot; name=&quot;email&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;join&quot; value=&quot;Join Network&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;networks&quot; /&gt;
        ///		&lt;inpu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_network_join {
            get {
                return ResourceManager.GetString("account_network_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///	&lt;h2&gt;&lt;a href=&quot;{U_NETWORK}&quot;&gt;{NETWORK_DISPLAY_NAME}&lt;/a&gt;&lt;/h2&gt;
        ///	&lt;div id=&quot;pane-profile&quot;&gt;
        ///		&lt;div id=&quot;pane-profile-overview&quot; class=&quot;pane&quot;&gt;
        ///			&lt;h3&gt;&lt;a href=&quot;{U_NETWORK}&quot;&gt;{NETWORK_DISPLAY_NAME}&lt;/a&gt;&lt;/h3&gt;
        ///			&lt;!-- IF U_JOIN --&gt;
        ///			&lt;p&gt;&lt;span id=&quot;join-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_JOIN}&quot;&gt;Join This Group&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///			&lt;!-- ENDIF --&gt;
        ///			&lt;!-- IF U_LEAVE --&gt;
        ///			&lt;p&gt;&lt;span id=&quot;leave-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_LEAVE}&quot;&gt;Leave This Group&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///			&lt;!-- ENDIF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewnetwork {
            get {
                return ResourceManager.GetString("viewnetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;h2&gt;{MEMBERS_TITLE}&lt;/h2&gt;
        ///
        ///&lt;!-- IF IS_WAITING_APPROVAL --&gt;
        ///&lt;h3&gt;Pending Memberships&lt;/h3&gt;
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN approval_list --&gt;
        ///&lt;!-- IF approval_list.INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{approval_list.U_PROFILE}&quot;&gt;{approval_list.USER_DISPLAY_NAME}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{approval_list.U_APPROVE}&quot;&gt;Approve Membership&lt;/a&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- END approval_li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewnetworkmemberlist {
            get {
                return ResourceManager.GetString("viewnetworkmemberlist", resourceCulture);
            }
        }
    }
}
