//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxSocial.Applications.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxSocial.Applications.Profile.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;My Address&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;My Address&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;address-1&quot;&gt;Address Line 1&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_ADDRESS_LINE_1}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;address-2&quot;&gt;Address Line 2&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_ADDRESS_LINE_2}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;town&quot;&gt;Suburb/Town/City&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_TOWN}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;state&quot;&gt;State/Province&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_STATE}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;post-code&quot;&gt;Post/Zip Code&lt;/label&gt;&lt;/dt&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_address_edit {
            get {
                return ResourceManager.GetString("account_address_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MANAGE_BLOCK_LIST}&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Name&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN block_list --&gt;
        ///&lt;!-- IF block_list.INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{block_list.NAME}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{block_list.U_UNBLOCK}&quot;&gt;{L_UNBLOCK}&lt;/a&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- END block_list --&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string account_blocklist_manage {
            get {
                return ResourceManager.GetString("account_blocklist_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MANAGE_BLOCK_LIST}&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Name&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN block_list --&gt;
        ///&lt;!-- IF block_list.INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{block_list.NAME}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{block_list.U_UNBLOCK}&quot;&gt;{L_UNBLOCK}&lt;/a&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- END block_list --&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string account_blocklist_manage1 {
            get {
                return ResourceManager.GetString("account_blocklist_manage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_CONTACT_DETAILS}&lt;/h3&gt;
        ///&lt;p&gt;{L_CONTACT_DETAILS_INFO}&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ADD_EMAIL_CONTACT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///  &lt;fieldset&gt;
        ///    &lt;legend&gt;{L_MY_CONTACT_DETAILS}&lt;/legend&gt;
        ///    &lt;dl&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;xmpp&quot;&gt;{L_XMPP}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;xmpp&quot; name=&quot;xmpp&quot; value=&quot;{S_XMPP}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;home-phone&quot;&gt;{L_HOME_PHONE}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;home-phone&quot; name=&quot;home-phone&quot; value=&quot;{S_HOME_PHONE}&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_contact {
            get {
                return ResourceManager.GetString("account_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_CONTACT_DETAILS}&lt;/h3&gt;
        ///&lt;p&gt;{L_CONTACT_DETAILS_INFO}&lt;/p&gt;
        ///
        ///&lt;!-- IF ADDRESS --&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;h2&gt;E-mail Addresses&lt;/h2&gt;
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Address&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN email_list --&gt;
        ///&lt;!-- IF email_list.INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{email_list.EMAIL}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{email_list.U_EDIT}&quot;&gt;{L_EDIT}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{email_list.U_DELETE}&quot;&gt;{L_DELETE}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_contact_manage {
            get {
                return ResourceManager.GetString("account_contact_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_CONTACT_DETAILS}&lt;/h3&gt;
        ///&lt;p&gt;{L_CONTACT_DETAILS_INFO}&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ADD_EMAIL_CONTACT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///  &lt;fieldset&gt;
        ///    &lt;legend&gt;{L_MY_CONTACT_DETAILS}&lt;/legend&gt;
        ///    &lt;dl&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;xmpp&quot;&gt;{L_XMPP}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;xmpp&quot; name=&quot;xmpp&quot; value=&quot;{S_XMPP}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;home-phone&quot;&gt;{L_HOME_PHONE}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;home-phone&quot; name=&quot;home-phone&quot; value=&quot;{S_HOME_PHONE}&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_contact1 {
            get {
                return ResourceManager.GetString("account_contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Display Picture&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Display Picture&lt;/legend&gt;
        ///    &lt;!-- IF I_DISPLAY_PICTURE --&gt;
        ///		&lt;p&gt;&lt;img src=&quot;{I_DISPLAY_PICTURE}&quot; alt=&quot;Display Picture&quot; /&gt;&lt;/p&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;photo-file&quot;&gt;Select File&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;file&quot; id=&quot;photo-file&quot; name=&quot;photo-file&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_display_picture {
            get {
                return ResourceManager.GetString("account_display_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;My Email&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;My Email&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;email-address&quot;&gt;Email Address&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_EMAIL}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;profile&quot; /&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;sub&quot; value=&quot;contact&quot; /&gt;
        ///		&lt;!-- IF EDIT --&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;mode&quot; value=&quot;edit-email&quot; /&gt;
        ///		&lt;!-- ELSE --&gt;
        ///		&lt;input type=&quot;hidden&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_email_edit {
            get {
                return ResourceManager.GetString("account_email_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Family&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Name&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN family_list --&gt;
        ///&lt;!-- IF family_list.INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{family_list.NAME}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{family_list.U_DELETE}&quot;&gt;Remove&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{family_list.U_BLOCK}&quot;&gt;Block&lt;/a&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- END family_list --&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string account_family_manage {
            get {
                return ResourceManager.GetString("account_family_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Invite a Friend to {SITE_TITLE}&lt;/h3&gt;
        ///&lt;p&gt;Invite a friend to join {SITE_TITLE}, just enter their e-mail address below:&lt;/p&gt;
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///&lt;fieldset&gt;
        ///		&lt;legend&gt;Invite a Friend to {SITE_TITLE}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;name&quot;&gt;Name:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;name&quot; name=&quot;name&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;email&quot;&gt;E-mail:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;email&quot; name=&quot;email&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;send&quot; value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_friend_invite {
            get {
                return ResourceManager.GetString("account_friend_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Friends&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Name&lt;/th&gt;
        ///	&lt;th&gt;Order&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN friend_list --&gt;
        ///&lt;!-- IF friend_list.INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{friend_list.U_PROFILE}&quot;&gt;{friend_list.NAME}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;{friend_list.ORDER}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{friend_list.U_PROMOTE}&quot;&gt;U&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{friend_list.U_DEMOTE}&quot;&gt;D&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{friend_list.U_D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_friends_manage {
            get {
                return ResourceManager.GetString("account_friends_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Lifestyle&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Lifestyle&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;religion&quot;&gt;Religion&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_RELIGION}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;maritial-status&quot;&gt;Maritial status&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_MARITIAL_STATUS}&lt;span id=&quot;maritial-verb&quot;&gt;&lt;/span&gt;&lt;input type=&quot;text&quot; name=&quot;relationship-with&quot; id=&quot;relationship-with&quot; value=&quot;{S_RELATIONSHIP_WITH}&quot;/&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;sexuality&quot;&gt;Sexuality&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_SEXUALITY}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_lifestyle {
            get {
                return ResourceManager.GetString("account_lifestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_NAME}&lt;/h3&gt;
        ///&lt;p&gt;Details of your real name are kept private between, you, your friends, and your family. People can search for your profile based on the name you give.&lt;/p&gt;
        ///&lt;p&gt;Your real name combined with your date of birth and hometown can be used to find you as together they are the most personally identifyable information about oneself. You should be careful who you give these pieces of information out to.&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_MY_NAME}&lt;/legen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_name {
            get {
                return ResourceManager.GetString("account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Profile Permissions&lt;/h3&gt;
        ///&lt;p&gt;You can make your profile private by unticking the `Other` box for read permissions.&lt;/p&gt;
        ///&lt;p&gt;To have your profile featured on the home page, you need to make sure that your profile can be read by Friends, Family, Group and Other.&lt;/p&gt;
        ///
        ///&lt;form action=&quot;/account/&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Profile Permissions&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label&gt;Permissions&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;
        ///				{S_PROFILE_PERMS}
        ///			&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_permissions {
            get {
                return ResourceManager.GetString("account_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;My Phone Number&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;My Phone Number&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;phone-number&quot;&gt;Phone Number&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_PHONE_NUMBER}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;phone-type&quot;&gt;Type&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_PHONE_TYPE}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;profile&quot; /&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;sub&quot; value=&quot;contact&quot; /&gt;
        ///		&lt;!-- IF EDIT --&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_phone_edit {
            get {
                return ResourceManager.GetString("account_phone_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_INFORMATION}&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_MY_INFORMATION}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;country&quot;&gt;{L_AUTO_BIOGRAPHY}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;
        ///				&lt;textarea id=&quot;auto-biography&quot; name=&quot;auto-biography&quot; style=&quot;margin: 0px; width: 100%; height: 160px; border: solid 1px #666666;&quot; rows=&quot;8&quot; cols=&quot;75&quot;&gt;{S_AUTO_BIOGRAPHY}&lt;/textarea&gt;
        ///				&lt;div style=&quot;background-image: url(&apos;/images/tab_shadow.png&apos;); background-repeat: repeat-x; position: relative; top: -2px; m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_profile {
            get {
                return ResourceManager.GetString("account_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Style&lt;/h3&gt;
        ///&lt;p&gt;Create a custom style. To see your style change to your profile, you must first turn on &apos;Show Custom Styles&apos; in your account preferences.&lt;/p&gt;
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Style&lt;/legend&gt;
        ///    &lt;!-- IF THEME_EDITOR --&gt;
        ///      &lt;h4&gt;&lt;span&gt;Theme&lt;/span&gt; &lt;small&gt;&lt;a href=&quot;?mode=standard&quot;&gt;Simple&lt;/a&gt;&lt;/small&gt; &lt;small&gt;&lt;a href=&quot;?mode=advanced&quot;&gt;Advanced&lt;/a&gt;&lt;/small&gt;&lt;/h4&gt;
        ///    &lt;div&gt;&lt;label&gt;&lt;input type=&quot;radio&quot; id=&quot;theme-default&quot; name=&quot;theme&quot; value=&quot;default&quot;{DEFAULT_SELECTE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_style {
            get {
                return ResourceManager.GetString("account_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///&lt;h2&gt;{L_STATUS_FEED}&lt;/h2&gt;
        ///&lt;!-- IF BREADCRUMBS --&gt;
        ///&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///&lt;ul&gt;
        ///  &lt;!-- BEGIN status_messages --&gt;
        ///  &lt;li&gt;
        ///    &lt;a href=&quot;/{USER_NAME}&quot;&gt;{USER_DISPLAY_NAME}&lt;/a&gt;
        ///    {status_messages.STATUS_MESSAGE} &lt;em&gt;{status_messages.STATUS_UPDATED}&lt;/em&gt;
        ///  &lt;/li&gt;
        ///  &lt;!-- END status_messages --&gt;
        ///&lt;/ul&gt;
        ///&lt;!-- INCLUDE page_footer.html --&gt;.
        /// </summary>
        internal static string viewstatusfeed {
            get {
                return ResourceManager.GetString("viewstatusfeed", resourceCulture);
            }
        }
    }
}
