//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxSocial.Applications.Gallery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxSocial.Applications.Gallery.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Galleries&lt;/h3&gt;
        ///
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///&lt;p class=&quot;action-buttons&quot;&gt;&lt;span class=&quot;actions-menu&quot;&gt;&lt;a onclick=&quot;return showPopupMenu(event, &apos;actions-menu&apos;);&quot;&gt;&lt;span&gt;&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;ul id=&quot;actions-menu&quot; class=&quot;popup-menu&quot;&gt;
        ///    &lt;!-- IF U_UPLOAD_PHOTO --&gt;
        ///    &lt;li&gt;&lt;a href=&quot;{U_UPLOAD_PHOTO}&quot;&gt;Upload Photo&lt;/a&gt;&lt;/li&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///    &lt;!-- IF U_NEW_GALLERY --&gt;
        ///    &lt;li&gt;&lt;a href=&quot;{U_NEW_GALLERY}&quot;&gt;New Gallery&lt;/a&gt;&lt;/li&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///    &lt;li&gt;&lt;a href=&quot;{U_EDIT_PERMISSIONS}&quot;&gt;{L_EDIT_PERMISSION [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_galleries {
            get {
                return ResourceManager.GetString("account_galleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- IF EDIT --&gt;
        ///&lt;h3&gt;Edit Gallery&lt;/h3&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;h3&gt;Add New Gallery&lt;/h3&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;!-- IF EDIT --&gt;
        ///		&lt;legend&gt;Edit Gallery&lt;/legend&gt;
        ///		&lt;!-- ELSE --&gt;
        ///		&lt;legend&gt;Add New Gallery&lt;/legend&gt;
        ///		&lt;!-- ENDIF --&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;title&quot;&gt;Title&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;title&quot; name=&quot;title&quot; value=&quot;{S_TITLE}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;description&quot;&gt;Description&lt;/label [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_galleries_add {
            get {
                return ResourceManager.GetString("account_galleries_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Galleries&lt;/h3&gt;
        ///
        ///&lt;p&gt;Gallery management for a group gallery is performed through the gallery provided, not through the group account panel.&lt;/p&gt;.
        /// </summary>
        internal static string account_galleries_group {
            get {
                return ResourceManager.GetString("account_galleries_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Upload Photo&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_FORM_ACTION}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Upload Photo&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;title&quot;&gt;Title&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;title&quot; name=&quot;title&quot; value=&quot;{S_PHOTO_TITLE}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///			&lt;!-- TODO: show picture thumbnail here --&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;description&quot;&gt;Description&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;
        ///				&lt;textarea id=&quot;description&quot; name=&quot;description&quot; style=&quot;margin: 0px; width: 100%; height: 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_galleries_photo_edit {
            get {
                return ResourceManager.GetString("account_galleries_photo_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Tag Photo&lt;/h3&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///&lt;!--
        ///var user_tags = new Array();
        ///	&lt;!-- BEGIN user_tags --&gt;
        ///  user_tags[{user_tags.INDEX}] = new Array({user_tags.TAG_ID}, {user_tags.TAG_X}, {user_tags.TAG_Y});
        ///  &lt;!-- END user_tags --&gt;
        ///--&gt;
        ///&lt;/script&gt;
        ///
        ///&lt;form action=&quot;{S_FORM_ACTION}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///	&lt;fieldset id=&quot;fieldlist&quot;&gt;
        ///		&lt;legend&gt;Tag Photo&lt;/legend&gt;
        ///		
        ///        &lt;!-- IF S_PHOTO_TITLE --&gt;
        ///			&lt;h4&gt;&lt;label for=&quot;title&quot;&gt;{S_PHOTO_TITLE}&lt;/label&gt;&lt;/h4&gt;
        ///        &lt;!-- ENDI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_galleries_photo_tag {
            get {
                return ResourceManager.GetString("account_galleries_photo_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_GALLERY_SETTINGS}&lt;/h3&gt;
        ///
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_GALLERY_SETTINGS}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;galleries&quot; /&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;sub&quot; value=&quot;settings&quot; /&gt;
        ///	&lt;/fieldset&gt;
        ///&lt;/form&gt;.
        /// </summary>
        internal static string account_galleries_settings {
            get {
                return ResourceManager.GetString("account_galleries_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Upload Photo&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Upload Photo&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;title&quot;&gt;Title&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;title&quot; name=&quot;title&quot; value=&quot;{S_TITLE}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;photo-file&quot;&gt;Select File&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;file&quot; id=&quot;photo-file&quot; name=&quot;photo-files[]&quot; multiple=&quot;multiple&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;description&quot;&gt;Description&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_galleries_upload {
            get {
                return ResourceManager.GetString("account_galleries_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;h2&gt;Upload Photo&lt;/h2&gt;
        ///
        ///&lt;form action=&quot;{S_FORM_ACTION}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Upload Photo&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;title&quot;&gt;Title&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;title&quot; name=&quot;title&quot; value=&quot;{S_TITLE}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;photo-file&quot;&gt;Select File&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;file&quot; id=&quot;photo-file&quot; name=&quot;photo-file&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;description&quot;&gt;Description&lt;/labe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string groupgalleryupload {
            get {
                return ResourceManager.GetString("groupgalleryupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- BEGIN photo_list --&gt;
        ///    &lt;li&gt;
        ///          &lt;div class=&quot;gallery-item&quot; style=&quot;text-align: center;&quot;&gt;
        ///            &lt;span class=&quot;photo-canvas&quot; style=&quot;display: inline-block; margin: auto; position: relative;&quot;&gt;
        ///            &lt;span class=&quot;gallery-title&quot;&gt;
        ///            &lt;h3&gt;
        ///                &lt;!-- IF photo_list.TITLE --&gt;
        ///                &lt;a class=&quot;photo-link&quot; href=&quot;{photo_list.PHOTO_URI}&quot; alt=&quot;{photo_list.TITLE}&quot;&gt;{photo_list.TITLE}&lt;/a&gt;
        ///                &lt;!-- ELSE --&gt;
        ///                &amp;nbsp;
        ///                &lt;!-- ENDI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pane_photo {
            get {
                return ResourceManager.GetString("pane_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- BEGIN photo_list --&gt;
        ///&lt;div class=&quot;ui-block-{photo_list.ABC}&quot; style=&quot;text-align: center;&quot;&gt;
        ///&lt;a href=&quot;{photo_list.PHOTO_URI}&quot;&gt;
        ///&lt;img src=&quot;{photo_list.TILE}&quot; alt=&quot;{photo_list.TITLE}&quot; width=&quot;100&quot; height=&quot;100&quot; /&gt;
        ///            &lt;!-- IF photo_list.TITLE --&gt;
        ///            &lt;p&gt;{photo_list.TITLE}&lt;/p&gt;
        ///            &lt;!-- ELSE --&gt;
        ///            &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///            &lt;!-- ENDIF --&gt;
        ///        &lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;!-- END photo_list --&gt;.
        /// </summary>
        internal static string pane_photo_mobile {
            get {
                return ResourceManager.GetString("pane_photo_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;script type=&quot;text/javascript&quot;&gt;
        ///      $(function () {
        ///          $(&quot;#album&quot;).buttonset();
        ///          $(&quot;.album-tab&quot;).hide();
        ///          $(&quot;#album-tab-0&quot;).show();
        ///      });
        ///
        ///      function switchAlbum(i) {
        ///          $(&quot;.album-tab&quot;).hide();
        ///          $(&quot;#album-tab-&quot; + i).show();
        ///          return false;
        ///      }
        ///
        ///      $(function () {
        ///          var filesList = [];
        ///          $(&apos;#fileupload&apos;).hide().fileupload({
        ///              dropZone: $(&quot;#upload&quot;),
        ///              disableImageResize: /Android(?!.*C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string postphoto {
            get {
                return ResourceManager.GetString("postphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;status-feed&quot;&gt;
        ///  &lt;!-- BEGIN status_messages --&gt;
        ///  &lt;li class=&quot;status-post&quot; id=&quot;status-{status_messages.ID}&quot;&gt;
        ///        &lt;!-- IF status_messages.USER_ICON --&gt;
        ///		&lt;div class=&quot;status-disp-pic&quot;&gt;
        ///			&lt;img src=&quot;{status_messages.USER_ICON}&quot; alt=&quot;{status_messages.USER_DISPLAY_NAME}&quot; /&gt;
        ///		&lt;/div&gt;
        ///		&lt;!-- ENDIF --&gt;
        ///        &lt;!-- IF $_IS_MOBILE --&gt;
        ///        &lt;div class=&quot;status-body&quot; style=&quot;cursor: pointer;&quot; onclick=&quot;window.location.href = &apos;{status_messages.URI}&apos;;&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///		&lt;div class=&quot;status- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string search_result_galleryitem {
            get {
                return ResourceManager.GetString("search_result_galleryitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF $_IS_DESKTOP AND USER_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info&quot; style=&quot;height: 100px; background-image: url(&apos;{USER_COVER_PHOTO}&apos;); background-position: 0 -50px;&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///  &lt;h2&gt;{GALLERY_TITLE}&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewgallery {
            get {
                return ResourceManager.GetString("viewgallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_MOBILE_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info no-icon&quot; style=&quot;height: 90px; background-image: url(&apos;{USER_MOBILE_COVER_PHOTO}&apos;);&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info no-icon&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;{GALLERY_TITLE}&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///    &lt;p class=&quot;action-buttons&quot;&gt;{BREADCRUMBS}&lt;span class=&quot;actions-menu&quot;&gt;&lt;a onclick=&quot;return showPopupMenu(event, &apos;actio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewgallery_mobile {
            get {
                return ResourceManager.GetString("viewgallery_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///	&lt;h2&gt;{USER_DISPLAY_NAME_OWNERSHIP} Gallery&lt;/h2&gt;
        ///	&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;
        ///	&lt;!-- IF U_UPLOAD_PHOTO --&gt;
        ///	&lt;div id=&quot;new-stuff&quot;&gt;
        ///		&lt;span id=&quot;new-photo&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_UPLOAD_PHOTO}&quot;&gt;Upload Photo&lt;/a&gt;&lt;/span&gt;
        ///	&lt;/div&gt;
        ///	&lt;!-- ENDIF --&gt;
        ///	&lt;!-- IF PAGINATION --&gt;
        ///	&lt;p&gt;&lt;strong&gt;Go to page:&lt;/strong&gt; {PAGINATION}&lt;/p&gt;
        ///	&lt;!-- ENDIF --&gt;
        ///	&lt;!-- IF PHOTOS --&gt;
        ///	&lt;ul id=&quot;photo-list&quot;&gt;
        ///		&lt;!-- BEGIN photo_list --&gt;
        ///		&lt;li&gt;
        ///			&lt;dl&gt;
        ///				&lt;dt&gt;&lt;a href=&quot;{photo_list.PHOTO_URI}&quot;&gt;&lt;img src [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewgroupgallery {
            get {
                return ResourceManager.GetString("viewgroupgallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF $_IS_DESKTOP AND USER_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info&quot; style=&quot;height: 100px; background-image: url(&apos;{USER_COVER_PHOTO}&apos;); background-position: 0 -50px;&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///  &lt;h2&gt;{PHOTO_TITLE}&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///        &lt;/div&gt;
        ///
        ///&lt;div i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewphoto {
            get {
                return ResourceManager.GetString("viewphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;/scripts/jquery.history.js&quot;&gt;&lt;/script&gt;
        ///
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_MOBILE_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info no-icon&quot; style=&quot;height: 90px; background-image: url(&apos;{USER_MOBILE_COVER_PHOTO}&apos;);&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info no-icon&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;{PHOTO_TITLE}&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///    &lt;p class=&quot;action-buttons&quot;&gt;{BREADCRUMBS} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewphoto_mobile {
            get {
                return ResourceManager.GetString("viewphoto_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;div id=&quot;profile-gallery-pane&quot; class=&quot;pane&quot;&gt;
        ///	&lt;h3&gt;Group Gallery ({PHOTOS})&lt;/h3&gt;
        ///	&lt;!-- IF PHOTOS --&gt;
        ///	&lt;ul id=&quot;photo-list&quot;&gt;
        ///		&lt;!-- BEGIN photo_list --&gt;
        ///		&lt;li&gt;
        ///			&lt;dl&gt;
        ///				&lt;dt&gt;&lt;a href=&quot;{photo_list.PHOTO_URI}&quot;&gt;&lt;img src=&quot;{photo_list.THUMBNAIL}&quot; alt=&quot;{photo_list.TITLE}&quot; /&gt;&lt;/a&gt;&lt;/dt&gt;
        ///			&lt;/dl&gt;
        ///		&lt;/li&gt;
        ///		&lt;!-- END photo_list --&gt;
        ///	&lt;/ul&gt;
        ///	&lt;!-- ENDIF --&gt;
        ///	&lt;div class=&quot;cheat-clear-left&quot;&gt;&lt;/div&gt;
        ///	&lt;p&gt;&lt;a href=&quot;{U_GROUP_GALLERY}&quot;&gt;View All Photos&lt;/a&gt;&lt;/p&gt;
        ///	&lt;/div&gt;.
        /// </summary>
        internal static string viewprofilegallery {
            get {
                return ResourceManager.GetString("viewprofilegallery", resourceCulture);
            }
        }
    }
}
