//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxSocial.Applications.Forum {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxSocial.Applications.Forum.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_DELETE_FORUM}&lt;/h3&gt;
        ///
        ///&lt;!-- IF ERROR --&gt;
        ///&lt;p class=&quot;error&quot;&gt;{ERROR}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///  &lt;fieldset&gt;
        ///    &lt;legend&gt;{L_DELETE_FORUM}&lt;/legend&gt;
        ///    &lt;dl&gt;
        ///      &lt;dt&gt;
        ///        &lt;label for=&quot;type&quot;&gt;{L_TOPICS_MOVETO_FORUM}&lt;/label&gt;
        ///      &lt;/dt&gt;
        ///      &lt;dd&gt;
        ///        {S_FORUM_PARENT}
        ///      &lt;/dd&gt;
        ///      &lt;dt&gt;&lt;/dt&gt;
        ///      &lt;dd&gt;
        ///        &lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;{L_DELETE}&quot; /&gt;
        ///      &lt;/dd&gt;
        ///    &lt;/dl&gt;
        ///    &lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;forum&quot; /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_forum_delete {
            get {
                return ResourceManager.GetString("account_forum_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- IF EDIT --&gt;
        ///&lt;h3&gt;{L_EDIT_FORUM}&lt;/h3&gt;
        ///&lt;p&gt;Manage forums.&lt;/p&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;h3&gt;{L_CREATE_NEW_FORUM}&lt;/h3&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- IF ERROR --&gt;
        ///&lt;p class=&quot;error&quot;&gt;{ERROR}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///  &lt;fieldset&gt;
        ///    &lt;!-- IF EDIT --&gt;
        ///    &lt;legend&gt;{L_EDIT_FORUM}&lt;/legend&gt;
        ///    &lt;!-- ELSE --&gt;
        ///    &lt;legend&gt;{L_CREATE_NEW_FORUM}&lt;/legend&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///    &lt;dl&gt;
        ///      &lt;dt&gt;
        ///        &lt;label for=&quot;type&quot;&gt;{L_FORUM_TYPE}&lt;/label&gt;
        ///      &lt;/dt&gt;
        ///      &lt;dd&gt;
        ///        {S_FORUM_TYP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_forum_edit {
            get {
                return ResourceManager.GetString("account_forum_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MANAGE_FORUMS}&lt;/h3&gt;
        ///&lt;p&gt;{L_MANAGE_FORUMS_PROSE}&lt;/p&gt;
        ///
        ///&lt;div id=&quot;new-stuff&quot;&gt;
        ///	&lt;!-- IF U_CREATE_FORUM --&gt;
        ///	&lt;span id=&quot;new-forum&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_CREATE_FORUM}&quot;&gt;{L_CREATE_NEW_FORUM}&lt;/a&gt;&lt;/span&gt;
        ///	&lt;!-- ENDIF --&gt;
        ///  &lt;span id=&quot;forum-permissions&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_PERMISSIONS}&quot;&gt;{L_EDIT_PERMISSIONS}&lt;/a&gt;&lt;/span&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;h3&gt;&lt;a href=&quot;{U_FORUM}&quot;&gt;{FORUM_TITLE}&lt;/a&gt;&lt;/h3&gt;
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;th&gt;{L_FORUM_CATEGORY}&lt;/th&gt;
        ///    &lt;th&gt;&lt;/th&gt;
        ///    &lt;!--&lt;th&gt;&lt;/th&gt;--&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_forum_manage {
            get {
                return ResourceManager.GetString("account_forum_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_FORUM_MEMBER}&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_FORUM_MEMBER}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;{L_USERNAME}&lt;/dt&gt;
        ///			&lt;dd&gt;{S_USERNAME}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;rank&quot;&gt;{L_RANK}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_RANK}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;signature&quot;&gt;{L_SIGNATURE}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;
        ///        {S_SIGNATURE}
        ///			&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;{L_SAVE}&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;forum&quot; /&gt;
        ///		&lt;input type=&quot;h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_forum_member_edit {
            get {
                return ResourceManager.GetString("account_forum_member_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_FORUM_MEMBERS}&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;th&gt;{L_RANK}&lt;/th&gt;
        ///    &lt;th&gt;{L_POSTS}&lt;/th&gt;
        ///    &lt;th&gt;&lt;/th&gt;
        ///    &lt;th&gt;&lt;/th&gt;
        ///  &lt;/tr&gt;
        ///  &lt;!-- BEGIN members --&gt;
        ///  &lt;!-- IF members.$_INDEX_EVEN --&gt;
        ///  &lt;tr class=&quot;even&quot;&gt;
        ///    &lt;!-- ELSE --&gt;
        ///    &lt;tr class=&quot;odd&quot;&gt;
        ///      &lt;!-- ENDIF --&gt;
        ///      &lt;td&gt;{members.DISPLAY_NAME}&lt;/td&gt;
        ///      &lt;td&gt;{members.POSTS}&lt;/td&gt;
        ///      &lt;td&gt;
        ///        &lt;a href=&quot;{members.U_EDIT}&quot;&gt;{L_EDIT}&lt;/a&gt;
        ///      &lt;/td&gt;
        ///      &lt;td&gt;
        ///        &lt;a href=&quot;{members.U_BAN}&quot;&gt;{L_BAN}&lt;/a&gt;
        ///      &lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_forum_member_manage {
            get {
                return ResourceManager.GetString("account_forum_member_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_FORUM_RANK}&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_FORUM_RANK}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;rank-title&quot;&gt;{L_RANK_TITLE}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_TITLE}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;min-posts&quot;&gt;{L_MINIMUM_POSTS}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_MINIMUM_POSTS}&lt;/dd&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;special&quot;&gt;{L_SPECIAL_RANK}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_SPECIAL}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;{L_SAVE}&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;modul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_forum_rank_edit {
            get {
                return ResourceManager.GetString("account_forum_rank_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_FORUM_RANKS}&lt;/h3&gt;
        ///
        ///&lt;div id=&quot;new-stuff&quot;&gt;
        ///	&lt;span id=&quot;new-rank&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_NEW_RANK}&quot;&gt;{L_NEW_RANK}&lt;/a&gt;&lt;/span&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;th&gt;{L_RANK}&lt;/th&gt;
        ///    &lt;th&gt;{L_SPECIAL}&lt;/th&gt;
        ///    &lt;th&gt;{L_MINIMUM_POSTS}&lt;/th&gt;
        ///    &lt;th&gt;&lt;/th&gt;
        ///    &lt;th&gt;&lt;/th&gt;
        ///  &lt;/tr&gt;
        ///  &lt;!-- BEGIN rank_list --&gt;
        ///  &lt;!-- IF rank_list.$_INDEX_EVEN --&gt;
        ///  &lt;tr class=&quot;even&quot;&gt;
        ///    &lt;!-- ELSE --&gt;
        ///    &lt;tr class=&quot;odd&quot;&gt;
        ///      &lt;!-- ENDIF --&gt;
        ///      &lt;td&gt;{rank_list.RANK}&lt;/td&gt;
        ///      &lt;td&gt;{rank_list.SP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_forum_ranks {
            get {
                return ResourceManager.GetString("account_forum_ranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_FORUM_SETTINGS}&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_FORUM_SETTINGS}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;topics-per-page&quot;&gt;{L_TOPICS_PER_PAGE}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;topics-per-page&quot; name=&quot;topics-per-page&quot; value=&quot;{S_TOPICS_PER_PAGE}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;posts-per-page&quot;&gt;{L_POSTS_PER_PAGE}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;posts-per-page&quot; name=&quot;posts-per-page&quot; value=&quot;{S_POSTS_PER_PAGE}&quot; style=&quot;width:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_forum_settings {
            get {
                return ResourceManager.GetString("account_forum_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- IF $_IS_MOBILE --&gt;
        ///&lt;p class=&quot;action-buttons&quot;&gt;{BREADCRUMBS}&lt;span class=&quot;actions-menu&quot;&gt;&lt;a onclick=&quot;return showPopupMenu(event, &apos;actions-menu&apos;);&quot;&gt;&lt;span&gt;&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///    &lt;ul id=&quot;actions-menu&quot; class=&quot;popup-menu&quot;&gt;
        ///    &lt;!-- IF U_NEW_TOPIC --&gt;
        ///        &lt;li&gt;&lt;a href=&quot;{U_NEW_TOPIC}&quot;&gt;{L_NEW_TOPIC}&lt;/a&gt;&lt;/li&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///    &lt;!-- IF U_NEW_REPLY --&gt;
        ///        &lt;li&gt;&lt;a href=&quot;{U_NEW_REPLY}&quot;&gt;{L_POST_REPLY}&lt;/a&gt;&lt;/li&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///    &lt;!-- IF IS_FORUM_MEMBER AND U_MARK_FORUMS_READ --&gt;
        ///        &lt;li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string forum_header {
            get {
                return ResourceManager.GetString("forum_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_MOBILE_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info no-icon&quot; style=&quot;height: 90px; background-image: url(&apos;{USER_MOBILE_COVER_PHOTO}&apos;);&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info no-icon&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;Forum Help&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;!--  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///&lt;!-- INCLUDE forum_header --&gt;
        ///&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;
        ///&lt;h2&gt;{ACCOUNT_TITLE}&lt;/h2&gt;
        ///&lt;!-- IF ERROR --&gt;
        ///&lt;p class=&quot;error&quot;&gt;{ERROR}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///&lt;!-- IF INFO --&gt;
        ///&lt;p class=&quot;information&quot;&gt;{INFO}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///&lt;!-- IF NO_PERMISSIONS --&gt;
        ///&lt;p class=&quot;no-permissions&quot;&gt;{NO_PERMISSIONS}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///&lt;!-- IF NO_CUSTOM_STYLE --&gt;
        ///&lt;p class=&quot;no-permissions&quot;&gt;{NO_CUSTOM_STYLE}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;div id=&quot;tabs&quot;&gt;
        ///  &lt;ul&gt;
        ///    &lt;!-- BEGIN module_list --&gt;
        ///    &lt;li&gt;
        ///      &lt;a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mcp {
            get {
                return ResourceManager.GetString("mcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Main&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_MCP}&quot; method=&quot;post&quot;&gt;
        ///  &lt;fieldset&gt;
        ///    &lt;legend&gt;Main&lt;/legend&gt;
        ///	&lt;!-- IF TOPICS --&gt;
        ///  &lt;p&gt;
        ///    {PAGINATION}
        ///  &lt;/p&gt;
        ///			&lt;ul id=&quot;topics&quot; class=&quot;pane mcp&quot;&gt;
        ///    &lt;li id=&quot;topic-head&quot;&gt;
        ///					&lt;dl class=&quot;title-row&quot;&gt;
        ///						&lt;dt&gt;&lt;div&gt;&amp;nbsp;&lt;/div&gt;&lt;/dt&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_VIEWS}&lt;/div&gt;&lt;/dd&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_REPLIES}&lt;/div&gt;&lt;/dd&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_LAST_POST}&lt;/div&gt;&lt;/dd&gt;
        ///            &lt;dd&gt;&lt;/dd&gt;
        ///      &lt;/dl&gt;
        ///    &lt;/li&gt;
        ///    &lt;!-- BEGIN topic_list --&gt;
        ///    &lt;li&gt;
        ///					&lt;dl class=&quot;icon&quot;&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mcp_main {
            get {
                return ResourceManager.GetString("mcp_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///&lt;!-- INCLUDE forum_header --&gt;
        ///&lt;h2&gt;Memberlist&lt;/h2&gt;
        ///
        ///&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;
        ///
        ///&lt;!-- IF PAGINATION --&gt;
        ///&lt;p&gt;
        ///  &lt;strong&gt;Go to page:&lt;/strong&gt; {PAGINATION}
        ///&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- IF MEMBERS --&gt;
        ///&lt;dl id=&quot;group-members&quot;&gt;
        ///  &lt;!-- BEGIN member_list --&gt;
        ///  &lt;dt class=&quot;member&quot;&gt;&lt;a href=&quot;{member_list.U_PROFILE}&quot;&gt;{member_list.USER_DISPLAY_NAME}&lt;/a&gt;&lt;/dt&gt;
        ///  &lt;dd&gt;&lt;a href=&quot;{member_list.U_PROFILE}&quot;&gt;{L_VIEW_PROFILE}&lt;/a&gt;&lt;/dd&gt;
        ///  &lt;dd&gt;{member_list.POSTS}&lt;/dd&gt;
        ///  &lt;dd&gt;{member_list.COUNTRY}&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string memberlist {
            get {
                return ResourceManager.GetString("memberlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP --&gt;
        ///&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_MOBILE_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info no-icon&quot; style=&quot;height: 90px; background-image: url(&apos;{USER_MOBILE_COVER_PHOTO}&apos;);&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info no-icon&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;{L_POST}&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;!-- IF $_IS_DES [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul id=&quot;posts&quot;&gt;
        ///  &lt;!-- BEGIN post_list --&gt;
        ///  &lt;li&gt;
        ///  	&lt;div class=&quot;post&quot;&gt;
        ///      &lt;div class=&quot;postbody&quot;&gt;
        ///  	&lt;h3 id=&quot;p{post_list.ID}&quot;&gt;&lt;a href=&quot;{post_list.URI}&quot;&gt;{post_list.SUBJECT}&lt;/a&gt;&lt;/h3&gt;
        ///  	&lt;p&gt;
        ///    &lt;!-- IF post_list.IS_READ --&gt;
        ///    &lt;img src=&quot;/images/posticon_read_sml.png&quot; alt=&quot;Read&quot; /&gt;
        ///    &lt;!-- ELSE --&gt;
        ///    &lt;img src=&quot;/images/posticon_unread_sml.png&quot; alt=&quot;New&quot; /&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///    by &lt;strong&gt;&lt;a href=&quot;{post_list.U_USER}&quot;&gt;{post_list.USER_DISPLAY_NAME}&lt;/a&gt;&lt;/strong&gt; on {post_list.POST_TIME}&lt;/p&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string topicpost {
            get {
                return ResourceManager.GetString("topicpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul id=&quot;posts&quot;&gt;
        ///  &lt;!-- BEGIN post_list --&gt;
        ///  &lt;li&gt;
        ///  	&lt;div class=&quot;post&quot;&gt;
        ///      &lt;div class=&quot;postbody&quot;&gt;
        ///  	&lt;h3 id=&quot;p{post_list.ID}&quot;&gt;&lt;a href=&quot;{post_list.URI}&quot;&gt;{post_list.SUBJECT}&lt;/a&gt;&lt;/h3&gt;
        ///  	&lt;p&gt;
        ///    &lt;!-- IF post_list.IS_READ --&gt;
        ///    &lt;img src=&quot;/images/posticon_read_sml.png&quot; alt=&quot;Read&quot; /&gt;
        ///    &lt;!-- ELSE --&gt;
        ///    &lt;img src=&quot;/images/posticon_unread_sml.png&quot; alt=&quot;New&quot; /&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///    by &lt;strong&gt;&lt;a href=&quot;{post_list.U_USER}&quot;&gt;{post_list.USER_DISPLAY_NAME}&lt;/a&gt;&lt;/strong&gt; on {post_list.POST_TIME}&lt;/p&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string topicpost_mobile {
            get {
                return ResourceManager.GetString("topicpost_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_MOBILE_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info no-icon&quot; style=&quot;height: 90px; background-image: url(&apos;{USER_MOBILE_COVER_PHOTO}&apos;);&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info no-icon&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;User Control Panel&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ucp {
            get {
                return ResourceManager.GetString("ucp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info&quot; style=&quot;height: 100px; background-image: url(&apos;{USER_COVER_PHOTO}&apos;); background-position: 0 -50px;&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;{FORUM_TITLE}&lt;/h2&gt;
        ///    &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;div id=&quot;page-body&quot;&gt;
        ///&lt;!-- INCLUDE forum_header --&gt;
        ///	
        ///	&lt;!-- IF R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewforum {
            get {
                return ResourceManager.GetString("viewforum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_MOBILE_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info no-icon&quot; style=&quot;height: 90px; background-image: url(&apos;{USER_MOBILE_COVER_PHOTO}&apos;);&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info no-icon&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;{GROUP_DISPLAY_NAME}&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;!-- INCLUDE forum_header --&gt;
        ///	&lt;h2&gt;{FORUM_TITLE}&lt;/h2&gt;
        ///	
        ///	&lt;!-- IF RULES --&gt;
        ///	&lt;div id=&quot;forum-rules&quot;&gt;
        ///		&lt;p&gt;&lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewforum_mobile {
            get {
                return ResourceManager.GetString("viewforum_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;div id=&quot;profile-forum-pane&quot; class=&quot;pane&quot;&gt;
        ///		&lt;h3&gt;&lt;a href=&quot;{U_FORUM}&quot;&gt;{L_FORUM}&lt;/a&gt;&lt;/h3&gt;
        ///    &lt;!-- IF topic_list --&gt;
        ///			&lt;ul id=&quot;topics&quot; class=&quot;pane&quot;&gt;
        ///    &lt;li id=&quot;topic-head&quot;&gt;
        ///					&lt;dl class=&quot;title-row&quot;&gt;
        ///						&lt;dt&gt;&lt;div&gt;&amp;nbsp;&lt;/div&gt;&lt;/dt&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_VIEWS}&lt;/div&gt;&lt;/dd&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_REPLIES}&lt;/div&gt;&lt;/dd&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_LAST_POST}&lt;/div&gt;&lt;/dd&gt;
        ///      &lt;/dl&gt;
        ///    &lt;/li&gt;
        ///    &lt;!-- BEGIN topic_list --&gt;
        ///    &lt;li&gt;
        ///					&lt;dl class=&quot;icon&quot;&gt;
        ///        &lt;dt&gt;
        ///
        ///    &lt;div class=&quot;topic-info&quot;&gt;
        ///    &lt;!-- IF topic_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewprofileforum {
            get {
                return ResourceManager.GetString("viewprofileforum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;div id=&quot;profile-forum-pane&quot; class=&quot;pane&quot;&gt;
        ///		&lt;h3&gt;&lt;a href=&quot;{U_FORUM}&quot;&gt;{L_FORUM}&lt;/a&gt;&lt;/h3&gt;
        ///    &lt;!-- IF topic_list --&gt;
        ///			&lt;ul id=&quot;topics&quot; class=&quot;pane&quot;&gt;
        ///    &lt;li id=&quot;topic-head&quot;&gt;
        ///					&lt;dl class=&quot;title-row&quot;&gt;
        ///						&lt;dt&gt;&lt;div&gt;&amp;nbsp;&lt;/div&gt;&lt;/dt&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_VIEWS}&lt;/div&gt;&lt;/dd&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_REPLIES}&lt;/div&gt;&lt;/dd&gt;
        ///						&lt;dd&gt;&lt;div&gt;{L_LAST_POST}&lt;/div&gt;&lt;/dd&gt;
        ///      &lt;/dl&gt;
        ///    &lt;/li&gt;
        ///    &lt;!-- BEGIN topic_list --&gt;
        ///    &lt;li&gt;
        ///					&lt;dl class=&quot;icon&quot;&gt;
        ///        &lt;dt&gt;
        ///
        ///    &lt;div class=&quot;topic-info&quot;&gt;
        ///    &lt;!-- IF topic_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewprofileforum_mobile {
            get {
                return ResourceManager.GetString("viewprofileforum_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info&quot; style=&quot;height: 100px; background-image: url(&apos;{USER_COVER_PHOTO}&apos;); background-position: 0 -50px;&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;{TOPIC_TITLE}&lt;/h2&gt;
        ///    &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;div id=&quot;page-body&quot;&gt;
        ///&lt;!-- INCLUDE forum_header --&gt;
        ///
        ///&lt;div class= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewtopic {
            get {
                return ResourceManager.GetString("viewtopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_MOBILE_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info no-icon&quot; style=&quot;height: 90px; background-image: url(&apos;{USER_MOBILE_COVER_PHOTO}&apos;);&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info no-icon&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;{TOPIC_TITLE}&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;!-- INCLUDE forum_header --&gt;
        ///
        ///&lt;p&gt;{PAGINATION}&lt;/p&gt;
        ///&lt;!-- IF POSTS --&gt;
        ///&lt;ul id=&quot;posts&quot;&gt;
        ///  &lt;!-- BEGIN post_list --&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewtopic_mobile {
            get {
                return ResourceManager.GetString("viewtopic_mobile", resourceCulture);
            }
        }
    }
}
