//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxSocial.Groups {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxSocial.Groups.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Appoint Group Officer&lt;/h3&gt;
        ///&lt;p&gt;Officers are special people in groups. They do not get any special privledges other than being grated a title. Enter a title for the officer you are appointing below.&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Appoint Group Officer&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;User&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;strong&gt;{S_USERNAME}&lt;/strong&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;title&quot;&gt;Officer Title&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;title&quot; name=&quot;title&quot; value=&quot;{S_TITLE}&quot; /&gt;&lt;/dd&gt;
        ///			&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_appoint_officer {
            get {
                return ResourceManager.GetString("account_group_appoint_officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Edit Group&lt;/h3&gt;
        ///&lt;!--p&gt;Here you can &lt;/p--&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Edit Group&lt;/legend&gt;
        ///		&lt;dl id=&quot;form-list&quot;&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;title&quot;&gt;Group Title:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd class=&quot;top&quot;&gt;&lt;input type=&quot;text&quot; name=&quot;title&quot; id=&quot;title&quot; size=&quot;64&quot; maxlength=&quot;64&quot; style=&quot;width: 350px; &quot;  value=&quot;{GROUP_DISPLAY_NAME}&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;category&quot;&gt;Group Category:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd class=&quot;top&quot;&gt;{S_CATEGORIES}&lt;/dd&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;label f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_edit {
            get {
                return ResourceManager.GetString("account_group_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Invite a Friend to a Group&lt;/h3&gt;
        ///&lt;p&gt;You can invite your friends to join the group below:&lt;/p&gt;
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///&lt;fieldset&gt;
        ///		&lt;legend&gt;Invite a Friend to a Group&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;name&quot;&gt;Username:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;username&quot; name=&quot;username&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Send Invite&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;groups&quot; /&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;sub&quot; value=&quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_invite {
            get {
                return ResourceManager.GetString("account_group_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Groups&lt;/h3&gt;
        ///&lt;p&gt;Manage groups you have operator status over. You can change the title, description, type, and category the group is in.&lt;/p&gt;
        ///&lt;span id=&quot;create-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_CREATE_GROUP}&quot;&gt;Create a New Group&lt;/a&gt;&lt;/span&gt;
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Title&lt;/th&gt;
        ///	&lt;th&gt;Type&lt;/th&gt;
        ///	&lt;th&gt;Members&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN group_list --&gt;
        ///&lt;!-- IF group_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_manage {
            get {
                return ResourceManager.GetString("account_group_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Group Memberships&lt;/h3&gt;
        ///&lt;p&gt;Manage the memberships to groups you are a member of.&lt;/p&gt;
        ///&lt;span id=&quot;join-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;/groups&quot;&gt;Join a Group&lt;/a&gt;&lt;/span&gt;
        ///&lt;!-- IF GROUP_MEMBERSHIPS --&gt;
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Title&lt;/th&gt;
        ///	&lt;th&gt;Type&lt;/th&gt;
        ///	&lt;th&gt;Members&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN group_list --&gt;
        ///&lt;!-- IF group_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{group_list.GROUP_DISPLAY_NAME}&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_membership {
            get {
                return ResourceManager.GetString("account_group_membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Style&lt;/h3&gt;
        ///&lt;p&gt;Create a custom group style. To see your style change to the group, you must first turn on &apos;Show Custom Styles&apos; in your account preferences.&lt;/p&gt;
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Style&lt;/legend&gt;
        ///			&lt;div id=&quot;advanced-style&quot;&gt;
        ///				&lt;textarea id=&quot;css-style&quot; name=&quot;css-style&quot; style=&quot;margin: 0px; width: 100%; height: 250px; border: solid 1px #666666;&quot; cols=&quot;70&quot; rows=&quot;15&quot;&gt;{STYLE}&lt;/textarea&gt;
        ///			&lt;/div&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;mode&quot; value=&quot;advanced&quot; /&gt;
        ///			&lt;p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_style {
            get {
                return ResourceManager.GetString("account_group_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Create User Group&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Edit Group&lt;/legend&gt;
        ///		&lt;dl id=&quot;form-list&quot;&gt;
        ///            &lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;title&quot;&gt;Group Title:&lt;/label&gt;&lt;/dt&gt;
        ///		    &lt;dd class=&quot;top&quot;&gt;{S_TITLE}&lt;/dd&gt;
        ///		    &lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;slug&quot;&gt;Group name slug:&lt;/label&gt;&lt;/dt&gt;
        ///		    &lt;dd class=&quot;top&quot;&gt;{S_SLUG}&lt;/dd&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;description&quot;&gt;Group Description:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd class=&quot;top&quot;&gt;
        ///				{S_DESCRIPTION}
        ///			&lt;/dd&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;lab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_subgroup_create {
            get {
                return ResourceManager.GetString("account_group_subgroup_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage User Groups&lt;/h3&gt;
        ///&lt;p&gt;Manage user groups that are in the current Group.&lt;/p&gt;
        ///&lt;span id=&quot;create-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_CREATE_USER_GROUP}&quot;&gt;Create a New User Group&lt;/a&gt;&lt;/span&gt;
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Title&lt;/th&gt;
        ///	&lt;th&gt;Type&lt;/th&gt;
        ///	&lt;th&gt;Members&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN group_list --&gt;
        ///&lt;!-- IF group_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{group_list.U_MEMBERS}&quot;&gt;{group_list.D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_subgroup_manage {
            get {
                return ResourceManager.GetString("account_group_subgroup_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string account_group_subgroup_members {
            get {
                return ResourceManager.GetString("account_group_subgroup_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- IF U_GROUP_ACCOUNT --&gt;
        ///&lt;a href=&quot;{U_GROUP_ACCOUNT}&quot;&gt;Group Administration Panel&lt;/a&gt;
        ///&lt;!-- ENDIF --&gt;.
        /// </summary>
        internal static string group_footer {
            get {
                return ResourceManager.GetString("group_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///&lt;h2&gt;Groups&lt;/h2&gt;
        ///
        ///&lt;!-- IF BREADCRUMBS --&gt;
        ///&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;span id=&quot;create-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_CREATE_GROUP}&quot;&gt;Create a New Group&lt;/a&gt;&lt;/span&gt;
        ///&lt;!-- IF CATEGORIES --&gt;
        ///&lt;h3&gt;Categories&lt;/h3&gt;
        ///&lt;ul&gt;
        ///	&lt;!-- BEGIN category_list --&gt;
        ///	&lt;li&gt;&lt;a href=&quot;{category_list.U_GROUP_CATEGORY}&quot;&gt;{category_list.TITLE}&lt;/a&gt; ({category_list.GROUPS})&lt;/li&gt;
        ///	&lt;!-- END category_list --&gt;
        ///&lt;/ul&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- IF CATEGORY_TITLE --&gt;
        ///&lt;h3&gt;{CATEGORY_TITLE}&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string groups_default {
            get {
                return ResourceManager.GetString("groups_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///	&lt;h2&gt;&lt;a href=&quot;{U_GROUP}&quot;&gt;{GROUP_DISPLAY_NAME}&lt;/a&gt;&lt;/h2&gt;
        ///	&lt;div id=&quot;pane-profile&quot;&gt;
        ///		&lt;div id=&quot;pane-profile-overview&quot; class=&quot;pane&quot;&gt;
        ///			&lt;h3&gt;&lt;a href=&quot;{U_GROUP}&quot;&gt;{GROUP_DISPLAY_NAME}&lt;/a&gt;&lt;/h3&gt;
        ///			&lt;dl&gt;
        ///			&lt;dt&gt;Group Created:&lt;/dt&gt;
        ///			&lt;dd&gt;{DATE_CREATED}&lt;/dd&gt;
        ///			&lt;/dl&gt;
        ///			&lt;!-- IF U_JOIN --&gt;
        ///			&lt;p&gt;&lt;span id=&quot;join-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_JOIN}&quot;&gt;Join This Group&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///			&lt;!-- ENDIF --&gt;
        ///			&lt;!-- IF U_LEAVE --&gt;
        ///			&lt;p&gt;&lt;span id=&quot;leave-group&quot; class=&quot;post-button&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewgroup {
            get {
                return ResourceManager.GetString("viewgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;h2&gt;{MEMBERS_TITLE}&lt;/h2&gt;
        ///&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;
        ///
        ///&lt;!-- IF IS_WAITING_APPROVAL --&gt;
        ///&lt;h3&gt;Pending Memberships&lt;/h3&gt;
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN approval_list --&gt;
        ///&lt;!-- IF approval_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{approval_list.U_PROFILE}&quot;&gt;{approval_list.USER_DISPLAY_NAME}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{approval_list.U_APPROVE}&quot;&gt;Approve Membership&lt;/a&gt;&lt;/td&gt;
        ///&lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewgroupmemberlist {
            get {
                return ResourceManager.GetString("viewgroupmemberlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;!-- IF HAS_GROUPS --&gt;
        ///		&lt;div id=&quot;pane-profile-groups&quot; class=&quot;pane&quot;&gt;
        ///			&lt;h3&gt;{USER_DISPLAY_NAME_OWNERSHIP} Groups&lt;/h3&gt;
        ///			&lt;ul&gt;
        ///				&lt;!-- BEGIN groups_list --&gt;
        ///				&lt;li&gt;&lt;a href=&quot;{groups_list.U_GROUP}&quot;&gt;{groups_list.TITLE}&lt;/a&gt;&lt;/li&gt;
        ///				&lt;!-- END groups_list --&gt;
        ///			&lt;/ul&gt;
        ///		&lt;/div&gt;
        ///		&lt;!-- ENDIF --&gt;.
        /// </summary>
        internal static string viewprofilegroups {
            get {
                return ResourceManager.GetString("viewprofilegroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;h2&gt;{SUBGROUP_TITLE}&lt;/h2&gt;
        ///
        ///&lt;!-- IF IS_WAITING_APPROVAL --&gt;
        ///
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;div id=&quot;member-filter-panel&quot;&gt;
        ///  &lt;p&gt;
        ///    &lt;a href=&quot;{U_FILTER_ALL}&quot;&gt;All&lt;/a&gt;
        ///    &lt;a href=&quot;{U_FILTER_BEGINS_A}&quot;&gt;A&lt;/a&gt;
        ///    &lt;a href=&quot;{U_FILTER_BEGINS_B}&quot;&gt;B&lt;/a&gt;
        ///    &lt;a href=&quot;{U_FILTER_BEGINS_C}&quot;&gt;C&lt;/a&gt;
        ///    &lt;a href=&quot;{U_FILTER_BEGINS_D}&quot;&gt;D&lt;/a&gt;
        ///    &lt;a href=&quot;{U_FILTER_BEGINS_E}&quot;&gt;E&lt;/a&gt;
        ///    &lt;a href=&quot;{U_FILTER_BEGINS_F}&quot;&gt;F&lt;/a&gt;
        ///    &lt;a href=&quot;{U_FILTER_BEGINS_G}&quot;&gt;G&lt;/a&gt;
        ///    &lt;a href=&quot;{U_FILTER_BEGINS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewsubgroup {
            get {
                return ResourceManager.GetString("viewsubgroup", resourceCulture);
            }
        }
    }
}
