//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blog.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE account_header.html --&gt;
        ///
        ///&lt;h3&gt;Manage Blog&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Posted&lt;/th&gt;
        ///	&lt;th&gt;Title&lt;/th&gt;
        ///	&lt;th&gt;Comments&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN blog_list --&gt;
        ///&lt;!-- IF blog_list.INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{blog_list.POSTED}&lt;/td&gt;
        ///	&lt;td&gt;{blog_list.TITLE}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{blog_list.U_COMMENTS}&quot;&gt;{blog_list.COMMENTS}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{blog_list.U_VIEW}&quot;&gt;View&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a hr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_blog_manage {
            get {
                return ResourceManager.GetString("account_blog_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE account_header.html --&gt;
        ///
        ///&lt;h3&gt;Write Blog Post&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;/account/&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Write Blog Post&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;title&quot;&gt;Title&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;title&quot; name=&quot;title&quot; value=&quot;{S_TITLE}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;post&quot;&gt;Page Text&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;
        ///				&lt;textarea id=&quot;post&quot; name=&quot;post&quot; style=&quot;margin: 0px; width: 100%; height: 250px; border: solid 1px #666666;&quot; cols=&quot;70&quot; rows=&quot;15&quot;&gt;{S_BLOG_TEXT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_post {
            get {
                return ResourceManager.GetString("account_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///&lt;div id=&quot;pane-profile&quot;&gt;
        ///	&lt;div id=&quot;pane-pages&quot; class=&quot;pane&quot;&gt;
        ///		&lt;h3&gt;Pages&lt;/h3&gt;
        ///		&lt;ul&gt;
        ///			&lt;li&gt;&lt;a href=&quot;{U_PROFILE}&quot;&gt;Profile&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;{U_BLOG}&quot;&gt;Blog&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;{U_GALLERY}&quot;&gt;Photo Gallery&lt;/a&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;a href=&quot;{U_FRIENDS}&quot;&gt;Friends&lt;/a&gt;&lt;/li&gt;
        ///			{PAGE_LIST}
        ///		&lt;/ul&gt;
        ///	&lt;/div&gt;
        ///	&lt;!-- IF ARCHIVES --&gt;
        ///	&lt;div id=&quot;pane-blog-archive&quot; class=&quot;pane&quot;&gt;
        ///		&lt;h3&gt;Archive&lt;/h3&gt;
        ///		&lt;ul&gt;
        ///		&lt;!-- BEGIN archive_list --&gt;
        ///			&lt;li&gt;&lt;a href=&quot;{archive_list.URL}&quot;&gt;{arch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewblog {
            get {
                return ResourceManager.GetString("viewblog", resourceCulture);
            }
        }
    }
}
