//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxSocial.Applications.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxSocial.Applications.Profile.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;My Address&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;My Address&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;address-1&quot;&gt;Address Line 1&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_ADDRESS_LINE_1}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;address-2&quot;&gt;Address Line 2&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_ADDRESS_LINE_2}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;town&quot;&gt;Suburb/Town/City&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_TOWN}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;state&quot;&gt;State/Province&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_STATE}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;post-code&quot;&gt;Post/Zip Code&lt;/label&gt;&lt;/dt&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_address_edit {
            get {
                return ResourceManager.GetString("account_address_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MANAGE_BLOCK_LIST}&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Name&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN block_list --&gt;
        ///&lt;!-- IF block_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{block_list.NAME}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{block_list.U_UNBLOCK}&quot;&gt;{L_UNBLOCK}&lt;/a&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- END block_list --&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string account_blocklist_manage {
            get {
                return ResourceManager.GetString("account_blocklist_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MANAGE_BLOCK_LIST}&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Name&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN block_list --&gt;
        ///&lt;!-- IF block_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{block_list.NAME}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{block_list.U_UNBLOCK}&quot;&gt;{L_UNBLOCK}&lt;/a&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- END block_list --&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string account_blocklist_manage1 {
            get {
                return ResourceManager.GetString("account_blocklist_manage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_CONTACT_DETAILS}&lt;/h3&gt;
        ///&lt;p&gt;{L_CONTACT_DETAILS_INFO}&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ADD_EMAIL_CONTACT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///  &lt;fieldset&gt;
        ///    &lt;legend&gt;{L_MY_CONTACT_DETAILS}&lt;/legend&gt;
        ///    &lt;dl&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;xmpp&quot;&gt;{L_XMPP}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;xmpp&quot; name=&quot;xmpp&quot; value=&quot;{S_XMPP}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;home-phone&quot;&gt;{L_HOME_PHONE}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;home-phone&quot; name=&quot;home-phone&quot; value=&quot;{S_HOME_PHONE}&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_contact {
            get {
                return ResourceManager.GetString("account_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_CONTACT_DETAILS}&lt;/h3&gt;
        ///&lt;p&gt;{L_CONTACT_DETAILS_INFO}&lt;/p&gt;
        ///
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///&lt;p class=&quot;action-buttons&quot;&gt;&lt;span class=&quot;actions-menu&quot;&gt;&lt;a onclick=&quot;return showPopupMenu(event, &apos;actions-menu&apos;);&quot;&gt;&lt;span&gt;&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;ul id=&quot;actions-menu&quot; class=&quot;popup-menu&quot;&gt;
        ///    &lt;li&gt;&lt;a href=&quot;{U_ADD_LINK}&quot;&gt;Add Link&lt;/a&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;a href=&quot;{U_ADD_EMAIL}&quot;&gt;Add E-mail Address&lt;/a&gt;&lt;/li&gt;
        ///    &lt;li&gt;&lt;a href=&quot;{U_ADD_PHONE}&quot;&gt;Add Phone Number&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;div id=&quot;new-stuff&quot;&gt;
        ///	&lt;span id=&quot;new-link&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_contact_manage {
            get {
                return ResourceManager.GetString("account_contact_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_CONTACT_DETAILS}&lt;/h3&gt;
        ///&lt;p&gt;{L_CONTACT_DETAILS_INFO}&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ADD_EMAIL_CONTACT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///  &lt;fieldset&gt;
        ///    &lt;legend&gt;{L_MY_CONTACT_DETAILS}&lt;/legend&gt;
        ///    &lt;dl&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;xmpp&quot;&gt;{L_XMPP}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;xmpp&quot; name=&quot;xmpp&quot; value=&quot;{S_XMPP}&quot; style=&quot;width: 100%;&quot; /&gt;&lt;/dd&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;home-phone&quot;&gt;{L_HOME_PHONE}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;home-phone&quot; name=&quot;home-phone&quot; value=&quot;{S_HOME_PHONE}&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_contact1 {
            get {
                return ResourceManager.GetString("account_contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Cover Photo&lt;/h3&gt;
        ///
        ///  &lt;script type=&quot;text/javascript&quot;&gt;
        ///      $(function () {
        ///          var offset = 0;
        ///          $(&quot;#crop-area&quot;).draggable({
        ///              containment: &quot;parent&quot;,
        ///              revert: true,
        ///              start: function (event, ui) {
        ///                  offset = ui.position.top;
        ///              },
        ///              drag: function (event, ui) {
        ///                  $(&quot;#crop-t&quot;).height($(&quot;#crop-t&quot;).height() + (ui.position.top - offset));
        ///                  $(&quot;#crop-b&quot;).height($(&quot;#crop-b&quot;).he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_cover_photo {
            get {
                return ResourceManager.GetString("account_cover_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Display Picture&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Display Picture&lt;/legend&gt;
        ///    &lt;!-- IF I_DISPLAY_PICTURE --&gt;
        ///		&lt;p&gt;&lt;img src=&quot;{I_DISPLAY_PICTURE}&quot; alt=&quot;Display Picture&quot; /&gt;&lt;/p&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;photo-file&quot;&gt;Select File&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;file&quot; id=&quot;photo-file&quot; name=&quot;photo-file&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_display_picture {
            get {
                return ResourceManager.GetString("account_display_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;My Email&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;My Email&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;email-address&quot;&gt;Email Address&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_EMAIL}&lt;/dd&gt;
        ///      &lt;dt&gt;&lt;label for=&quot;email-type&quot;&gt;Type&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_EMAIL_TYPE}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;profile&quot; /&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;sub&quot; value=&quot;contact&quot; /&gt;
        ///		&lt;!-- IF EDIT --&gt;
        ///    &lt;input type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_email_edit {
            get {
                return ResourceManager.GetString("account_email_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Family&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;Name&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN family_list --&gt;
        ///&lt;!-- IF family_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;{family_list.NAME}&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{family_list.U_DELETE}&quot;&gt;Remove&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{family_list.U_BLOCK}&quot;&gt;Block&lt;/a&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- END family_list --&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string account_family_manage {
            get {
                return ResourceManager.GetString("account_family_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Invite a Friend to {SITE_TITLE}&lt;/h3&gt;
        ///
        ///&lt;!-- IF S_CANNOT_INVITE --&gt;
        ///&lt;p&gt;Sorry, you have no invites left to send.&lt;/p&gt;
        ///&lt;!-- ELSE --&gt;
        ///
        ///&lt;!-- IF MAX_INVITES --&gt;
        ///&lt;p&gt;You have sent {INVITES_SENT} of {MAX_INVITES} invites.&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;p&gt;Invite a friend to join {SITE_TITLE}, just enter their e-mail address below:&lt;/p&gt;
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///&lt;fieldset&gt;
        ///		&lt;legend&gt;Invite a Friend to {SITE_TITLE}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;name&quot;&gt;Name:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_friend_invite {
            get {
                return ResourceManager.GetString("account_friend_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MANAGE_FRIENDS}&lt;/h3&gt;
        ///
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///&lt;!-- BEGIN friend_list --&gt;
        ///    &lt;ul id=&quot;friends-more-{friend_list.ID}&quot; class=&quot;popup-menu&quot;&gt;
        ///        &lt;li&gt;&lt;a href=&quot;{friend_list.U_PROMOTE}&quot;&gt;{L_MOVE_UP}&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;{friend_list.U_DEMOTE}&quot;&gt;{L_MOVE_DOWN}&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;{friend_list.U_BLOCK}&quot;&gt;{L_BLOCK_USER}&lt;/a&gt;&lt;/li&gt;
        ///    &lt;/ul&gt;
        ///&lt;!-- END friend_list --&gt;
        ///
        ///&lt;ul class=&quot;list&quot;&gt;
        ///&lt;!-- BEGIN friend_list --&gt;
        ///&lt;li class=&quot;list-item icon&quot;&gt;
        ///    &lt;p&gt;
        ///        &lt;!-- IF friend_list.ICON - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_friends_manage {
            get {
                return ResourceManager.GetString("account_friends_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Cover Photo&lt;/h3&gt;
        ///
        ///  &lt;script type=&quot;text/javascript&quot;&gt;
        ///      $(function () {
        ///          var offset = 0;
        ///          $(&quot;#crop-area&quot;).draggable({
        ///              containment: &quot;parent&quot;,
        ///              revert: true,
        ///              start: function (event, ui) {
        ///                  offset = ui.position.top;
        ///              },
        ///              drag: function (event, ui) {
        ///                  $(&quot;#crop-t&quot;).height($(&quot;#crop-t&quot;).height() + (ui.position.top - offset));
        ///                  $(&quot;#crop-b&quot;).height($(&quot;#crop-b&quot;).he [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_cover_photo {
            get {
                return ResourceManager.GetString("account_group_cover_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Display Picture&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Display Picture&lt;/legend&gt;
        ///    &lt;!-- IF I_DISPLAY_PICTURE --&gt;
        ///		&lt;p&gt;&lt;img src=&quot;{I_DISPLAY_PICTURE}&quot; alt=&quot;Display Picture&quot; /&gt;&lt;/p&gt;
        ///    &lt;!-- ENDIF --&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;photo-file&quot;&gt;Select File&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;file&quot; id=&quot;photo-file&quot; name=&quot;photo-file&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_icon {
            get {
                return ResourceManager.GetString("account_group_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_LIFESTYLE}&lt;/h3&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    $(function () {
        ///        $(&quot;.account-pane input[type=&apos;submit&apos;]&quot;).hide();
        ///    });
        ///&lt;/script&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_LIFESTYLE}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;religion&quot;&gt;{L_RELIGION}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_RELIGION}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;maritial-status&quot;&gt;{L_MARITIAL_STATUS}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_MARITIAL_STATUS}&lt;span id=&quot;maritial-verb&quot;&gt;&lt;/span&gt; {S_RELATION}&lt;/dd&gt;
        ///            &lt;dt&gt;&lt;label&gt;{L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_lifestyle {
            get {
                return ResourceManager.GetString("account_lifestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Link&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Link&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;link-address&quot;&gt;Link&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_LINK}&lt;/dd&gt;
        ///            &lt;dt&gt;&lt;label for=&quot;link-title&quot;&gt;Title&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_TITLE}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;profile&quot; /&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;sub&quot; value=&quot;contact&quot; /&gt;
        ///		&lt;!-- IF EDIT --&gt;
        ///    &lt;input type=&quot;hidden&quot; name=&quot;id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_link_edit {
            get {
                return ResourceManager.GetString("account_link_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_NAME}&lt;/h3&gt;
        ///&lt;p&gt;Details of your real name are kept private between, you, your friends, and your family. People can search for your profile based on the name you give.&lt;/p&gt;
        ///&lt;p&gt;Your real name combined with your date of birth and hometown can be used to find you as together they are the most personally identifyable information about oneself. You should be careful who you give these pieces of information out to.&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_MY_NAME}&lt;/legen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_name {
            get {
                return ResourceManager.GetString("account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Profile Permissions&lt;/h3&gt;
        ///&lt;p&gt;You can make your profile private by unticking the `Other` box for read permissions.&lt;/p&gt;
        ///&lt;p&gt;To have your profile featured on the home page, you need to make sure that your profile can be read by Friends, Family, Group and Other.&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Profile Permissions&lt;/legend&gt;
        ///        &lt;h4&gt;&lt;label&gt;Permissions&lt;/label&gt;&lt;/h4&gt;
        ///        {S_PROFILE_PERMS}
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_permissions {
            get {
                return ResourceManager.GetString("account_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;My Phone Number&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;My Phone Number&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;phone-number&quot;&gt;Phone Number&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_PHONE_NUMBER}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;phone-type&quot;&gt;Type&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_PHONE_TYPE}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Save&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;profile&quot; /&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;sub&quot; value=&quot;contact&quot; /&gt;
        ///		&lt;!-- IF EDIT --&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_phone_edit {
            get {
                return ResourceManager.GetString("account_phone_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string account_phone_verify {
            get {
                return ResourceManager.GetString("account_phone_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;{L_MY_INFORMATION}&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;{L_MY_INFORMATION}&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;country&quot;&gt;{L_AUTOBIOGRAPHY}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;
        ///				&lt;textarea id=&quot;auto-biography&quot; name=&quot;auto-biography&quot; style=&quot;margin: 0px; width: 100%; height: 160px;&quot; rows=&quot;8&quot; cols=&quot;75&quot;&gt;{S_AUTO_BIOGRAPHY}&lt;/textarea&gt;
        ///			&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;country&quot;&gt;{L_COUNTRY}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;{S_COUNTRY}&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label&gt;{L_DATE_OF_BIRTH}&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;
        ///				&lt;label [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_profile {
            get {
                return ResourceManager.GetString("account_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot; src=&quot;/scripts/raphael-min.js&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;/scripts/colorwheel.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    .colortextbox
        ///    {
        ///        position: relative;
        ///        padding: 0;
        ///        margin: 0;
        ///    }
        ///    
        ///    .colortextbox input[type=&quot;text&quot;]
        ///    {
        ///        width: 60px;
        ///        padding: 4px;
        ///        margin: 0;
        ///        outline: none;
        ///    }
        ///    
        ///    input[type=&quot;text&quot;].colorwheelinput
        ///    {
        ///        width: 101px;
        ///        border-r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_style {
            get {
                return ResourceManager.GetString("account_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;div id=&quot;compose-status&quot;&gt;
        ///        &lt;div id=&quot;status-div&quot;&gt;
        ///		&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot; id=&quot;status-form&quot; onsubmit=&quot;return SendAction(&apos;{USER_DISPLAY_NAME}&apos;);&quot;&gt;
        ///			&lt;p&gt;&lt;textarea id=&quot;message&quot; name=&quot;message&quot; class=&quot;blur&quot; style=&quot;width: 100%; height: 24px; overflow-y: hidden;&quot; rows=&quot;1&quot; cols=&quot;75&quot; onfocus=&quot;$(this).css(&apos;height&apos;, &apos;78px&apos;).css(&apos;overflow-y&apos;, &apos;auto&apos;); $(this).parent().siblings(&apos;.status-buttons&apos;).show();&quot;&gt;{L_SHARE_SOMETHING_INTERESTING}&lt;/textarea&gt;
        ///            &lt;input type=&quot;hidden&quot; name=&quot;aclm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poststatusmessage {
            get {
                return ResourceManager.GetString("poststatusmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;div id=&quot;today-friends&quot; style=&quot;border: solid 1px #EEEEEE; margin-bottom: 5px;&quot;&gt;
        ///		&lt;h4&gt;{L_FRIENDS}&lt;/h4&gt;
        ///	&lt;!-- IF friend_list --&gt;
        ///	&lt;ul id=&quot;small-friends&quot;&gt;
        ///	&lt;!-- BEGIN friend_list --&gt;
        ///		&lt;li&gt;
        ///			&lt;a href=&quot;{friend_list.U_PROFILE}&quot;&gt;
        ///				&lt;!-- IF friend_list.ICON --&gt;
        ///				&lt;img src=&quot;{friend_list.ICON}&quot; data-at2x=&quot;{friend_list.TILE}&quot; alt=&quot;{friend_list.USER_DISPLAY_NAME}&quot; title=&quot;{friend_list.USER_DISPLAY_NAME}&quot; width=&quot;40&quot; height=&quot;40&quot; /&gt;
        ///				&lt;!-- ELSE --&gt;
        ///				&lt;img src=&quot;/images/no_picture_100.png&quot; alt=&quot;{friend_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string todayfriendpanel {
            get {
                return ResourceManager.GetString("todayfriendpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- INCLUDE primitive_header.html --&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///&lt;!--
        ///    $(document).ready(function () {
        ///        $(&apos;#message&apos;).focus().val(&apos;is &apos;).outerWidth($(&apos;#status-div&apos;).width() - $(&apos;#status-submit&apos;).outerWidth(true));
        ///    });
        ///    nid = {NEWEST_ID};
        ///--&gt;
        ///&lt;/script&gt;
        ///
        ///	&lt;div id=&quot;pane-profile&quot;&gt;
        ///		&lt;div id=&quot;pane-pages&quot; class=&quot;pane&quot;&gt;
        ///			&lt;h3&gt;{L_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewfeed {
            get {
                return ResourceManager.GetString("viewfeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- INCLUDE primitive_header.html --&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///&lt;!--
        ///    $(document).ready(function () {
        ///        $(&apos;#message&apos;).focus().val(&apos;is &apos;).outerWidth($(&apos;#status-div&apos;).width() - $(&apos;#status-submit&apos;).outerWidth(true));
        ///    });
        ///--&gt;
        ///&lt;/script&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP --&gt;
        ///	&lt;div id=&quot;pane-profile&quot;&gt;
        ///		&lt;div id=&quot;pane-pages&quot; class=&quot;pane&quot;&gt;
        ///			&lt;h3&gt;{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewstatusfeed {
            get {
                return ResourceManager.GetString("viewstatusfeed", resourceCulture);
            }
        }
    }
}
