//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxSocial.Groups {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoxSocial.Groups.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Appoint Group Officer&lt;/h3&gt;
        ///&lt;p&gt;Officers are special people in groups. They do not get any special privledges other than being grated a title. Enter a title for the officer you are appointing below.&lt;/p&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Appoint Group Officer&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;User&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;strong&gt;{S_USERNAME}&lt;/strong&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;title&quot;&gt;Officer Title&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;title&quot; name=&quot;title&quot; value=&quot;{S_TITLE}&quot; /&gt;&lt;/dd&gt;
        ///			&lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_appoint_officer {
            get {
                return ResourceManager.GetString("account_group_appoint_officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Edit Group&lt;/h3&gt;
        ///&lt;!--p&gt;Here you can &lt;/p--&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Edit Group&lt;/legend&gt;
        ///		&lt;dl id=&quot;form-list&quot;&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;title&quot;&gt;Group Title:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd class=&quot;top&quot;&gt;&lt;input type=&quot;text&quot; name=&quot;title&quot; id=&quot;title&quot; size=&quot;64&quot; maxlength=&quot;64&quot; style=&quot;width: 350px; &quot;  value=&quot;{GROUP_DISPLAY_NAME}&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;category&quot;&gt;Group Category:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd class=&quot;top&quot;&gt;{S_CATEGORIES}&lt;/dd&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;label f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_edit {
            get {
                return ResourceManager.GetString("account_group_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Invite a Friend to a Group&lt;/h3&gt;
        ///&lt;p&gt;You can invite your friends to join the group below:&lt;/p&gt;
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///&lt;fieldset&gt;
        ///		&lt;legend&gt;Invite a Friend to a Group&lt;/legend&gt;
        ///		&lt;dl&gt;
        ///			&lt;dt&gt;&lt;label for=&quot;name&quot;&gt;Username:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;text&quot; id=&quot;username&quot; name=&quot;username&quot; /&gt;&lt;/dd&gt;
        ///			&lt;dt&gt;&lt;/dt&gt;
        ///			&lt;dd&gt;&lt;input type=&quot;submit&quot; name=&quot;save&quot; value=&quot;Send Invite&quot; /&gt;&lt;/dd&gt;
        ///		&lt;/dl&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;module&quot; value=&quot;groups&quot; /&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;sub&quot; value=&quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_invite {
            get {
                return ResourceManager.GetString("account_group_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Groups&lt;/h3&gt;
        ///&lt;p&gt;Manage groups you have operator status over. You can change the title, description, type, and category the group is in.&lt;/p&gt;
        ///
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///&lt;p class=&quot;action-buttons&quot;&gt;&lt;span class=&quot;actions-menu&quot;&gt;&lt;a onclick=&quot;return showPopupMenu(event, &apos;actions-menu&apos;);&quot;&gt;&lt;span&gt;&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;ul id=&quot;actions-menu&quot; class=&quot;popup-menu&quot;&gt;
        ///    &lt;li&gt;&lt;a href=&quot;{U_CREATE_GROUP}&quot;&gt;Create a New Group&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;div id=&quot;new-stuff&quot;&gt;
        ///    &lt;span id=&quot;create-group&quot; class=&quot;post-b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_manage {
            get {
                return ResourceManager.GetString("account_group_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Group Memberships&lt;/h3&gt;
        ///&lt;p&gt;Manage the memberships to groups you are a member of.&lt;/p&gt;
        ///
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///&lt;p class=&quot;action-buttons&quot;&gt;&lt;span class=&quot;actions-menu&quot;&gt;&lt;a onclick=&quot;return showPopupMenu(event, &apos;actions-menu&apos;);&quot;&gt;&lt;span&gt;&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;ul id=&quot;actions-menu&quot; class=&quot;popup-menu&quot;&gt;
        ///    &lt;li&gt;&lt;a href=&quot;/groups&quot;&gt;Join a Group&lt;/a&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;div id=&quot;new-stuff&quot;&gt;
        ///&lt;span id=&quot;join-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;/groups&quot;&gt;Join a Group&lt;/a&gt;&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_membership {
            get {
                return ResourceManager.GetString("account_group_membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Style&lt;/h3&gt;
        ///&lt;p&gt;Create a custom group style. To see your style change to the group, you must first turn on &apos;Show Custom Styles&apos; in your account preferences.&lt;/p&gt;
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Style&lt;/legend&gt;
        ///			&lt;div id=&quot;advanced-style&quot;&gt;
        ///				&lt;textarea id=&quot;css-style&quot; name=&quot;css-style&quot; style=&quot;margin: 0px; width: 100%; height: 250px; border: solid 1px #666666;&quot; cols=&quot;70&quot; rows=&quot;15&quot;&gt;{STYLE}&lt;/textarea&gt;
        ///			&lt;/div&gt;
        ///		&lt;input type=&quot;hidden&quot; name=&quot;mode&quot; value=&quot;advanced&quot; /&gt;
        ///			&lt;p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_style {
            get {
                return ResourceManager.GetString("account_group_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Create Sub User Group&lt;/h3&gt;
        ///
        ///&lt;form action=&quot;{S_ACCOUNT}&quot; method=&quot;post&quot;&gt;
        ///	&lt;fieldset&gt;
        ///		&lt;legend&gt;Edit Group&lt;/legend&gt;
        ///		&lt;dl id=&quot;form-list&quot;&gt;
        ///            &lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;title&quot;&gt;Group Title:&lt;/label&gt;&lt;/dt&gt;
        ///		    &lt;dd class=&quot;top&quot;&gt;{S_TITLE}&lt;/dd&gt;
        ///		    &lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;slug&quot;&gt;Group name slug:&lt;/label&gt;&lt;/dt&gt;
        ///		    &lt;dd class=&quot;top&quot;&gt;{S_SLUG}&lt;/dd&gt;
        ///			&lt;dt class=&quot;top&quot;&gt;&lt;label for=&quot;description&quot;&gt;Group Description:&lt;/label&gt;&lt;/dt&gt;
        ///			&lt;dd class=&quot;top&quot;&gt;
        ///				{S_DESCRIPTION}
        ///			&lt;/dd&gt;
        ///			&lt;dt class=&quot;top&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_subgroup_create {
            get {
                return ResourceManager.GetString("account_group_subgroup_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Sub User Groups&lt;/h3&gt;
        ///&lt;p&gt;Manage user groups that are in the current Group. Sub user groups allow you to group members of your community for various roles and permissions.&lt;/p&gt;
        ///&lt;span id=&quot;create-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_CREATE_USER_GROUP}&quot;&gt;{L_CREATE_NEW_GROUP}&lt;/a&gt;&lt;/span&gt;
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;{L_TITLE}&lt;/th&gt;
        ///	&lt;th&gt;{L_TYPE}&lt;/th&gt;
        ///	&lt;th&gt;{L_MEMBERS}&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///	&lt;th&gt;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- BEGIN group_list --&gt;
        ///&lt;!-- IF group_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_subgroup_manage {
            get {
                return ResourceManager.GetString("account_group_subgroup_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Manage Sub User Groups Members :: {SUBGROUP_DISPLAY_NAME}&lt;/h3&gt;
        ///
        ///&lt;table style=&quot;width: 100%&quot;&gt;
        ///&lt;tr&gt;
        ///	&lt;th&gt;User&lt;/th&gt;
        ///	&lt;th&gt;Default Group for Member&lt;/th&gt;
        ///	&lt;th&gt;Joined&lt;/th&gt;
        ///	&lt;th&gt;&amp;nbsp;&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///	&lt;th colspan=&quot;4&quot;&gt;Group Leaders&lt;/th&gt;
        ///&lt;/tr&gt;
        ///&lt;!-- IF leader_list --&gt;
        ///&lt;!-- BEGIN leader_list --&gt;
        ///&lt;!-- IF leader_list.$_INDEX_EVEN --&gt;
        ///&lt;tr class=&quot;even&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;tr class=&quot;odd&quot;&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;td&gt;&lt;a href=&quot;{leader_list.U_USER}&quot;&gt;{leader_list.DISPLAY_NAME}&lt;/a&gt;&lt;/td&gt;
        ///	&lt;td&gt;{leader_list.DEFAULT_GROU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string account_group_subgroup_members {
            get {
                return ResourceManager.GetString("account_group_subgroup_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- IF U_GROUP_ACCOUNT --&gt;
        ///&lt;div style=&quot;margin: 1em;&quot;&gt;
        ///&lt;a href=&quot;{U_GROUP_ACCOUNT}&quot;&gt;Group Administration Panel&lt;/a&gt;
        ///&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;.
        /// </summary>
        internal static string group_footer {
            get {
                return ResourceManager.GetString("group_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;
        ///&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;h2&gt;Groups&lt;/h2&gt;
        ///
        ///&lt;span id=&quot;create-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_CREATE_GROUP}&quot;&gt;Create a New Group&lt;/a&gt;&lt;/span&gt;
        ///&lt;!-- IF CATEGORIES --&gt;
        ///&lt;h3&gt;Categories&lt;/h3&gt;
        ///&lt;!-- IF $_IS_MOBILE --&gt;
        ///&lt;ul class=&quot;list&quot;&gt;
        ///&lt;!-- ELSE --&gt;
        ///&lt;ul&gt;
        ///&lt;!-- ENDIF --&gt;
        ///	&lt;!-- BEGIN category_list --&gt;
        ///    &lt;!-- IF $_IS_MOBILE --&gt;
        ///    &lt;li class=&quot;list-item icon&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string groups_default {
            get {
                return ResourceManager.GetString("groups_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;div id=&quot;today-groups&quot; style=&quot;border: solid 1px #EEEEEE; margin-bottom: 5px;&quot;&gt;
        ///		&lt;h4&gt;{L_GROUPS}&lt;/h4&gt;
        ///	&lt;!-- IF groups_list --&gt;
        ///	&lt;ul id=&quot;small-groups&quot;&gt;
        ///	&lt;!-- BEGIN groups_list --&gt;
        ///		&lt;li&gt;
        ///			&lt;a href=&quot;{groups_list.U_GROUP}&quot;&gt;
        ///				&lt;!-- IF groups_list.ICON --&gt;
        ///				&lt;img src=&quot;{groups_list.ICON}&quot; data-at2x=&quot;{groups_list.TILE}&quot; alt=&quot;{groups_list.TITLE}&quot; title=&quot;{groups_list.TITLE}&quot; /&gt;
        ///				&lt;!-- ELSE --&gt;
        ///				&lt;img src=&quot;/images/no_picture_100.png&quot; alt=&quot;{groups_list.TITLE}&quot; title=&quot;{groups_list.TITLE}&quot; /&gt;
        ///				&lt;!- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string todaygrouppanel {
            get {
                return ResourceManager.GetString("todaygrouppanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///    &lt;!-- IF $_IS_MOBILE --&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF USER_MOBILE_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info no-icon&quot; style=&quot;height: 90px; background-image: url(&apos;{USER_MOBILE_COVER_PHOTO}&apos;);&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info no-icon&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///        &lt;h2&gt;{GROUP_DISPLAY_NAME}&lt;/h2&gt;
        ///        &lt;/div&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewgroup {
            get {
                return ResourceManager.GetString("viewgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;!-- IF $_IS_DESKTOP --&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF $_IS_DESKTOP AND USER_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info&quot; style=&quot;height: 100px; background-image: url(&apos;{USER_COVER_PHOTO}&apos;); background-position: 0 -50px;&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///			&lt;h2&gt;{MEMBERS_TITLE}&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewgroupmemberlist {
            get {
                return ResourceManager.GetString("viewgroupmemberlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;!-- IF $_IS_DESKTOP AND BREADCRUMBS --&gt;
        ///&lt;div class=&quot;breadcrumbs&quot;&gt;&lt;p&gt;{BREADCRUMBS}&lt;/p&gt;&lt;/div&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;!-- IF $_IS_DESKTOP --&gt;
        ///	&lt;div id=&quot;overview-profile&quot; class=&quot;pane&quot;&gt;
        ///        &lt;!-- IF $_IS_DESKTOP AND USER_COVER_PHOTO --&gt;
        ///		&lt;div class=&quot;info&quot; style=&quot;height: 100px; background-image: url(&apos;{USER_COVER_PHOTO}&apos;); background-position: 0 -50px;&quot;&gt;
        ///        &lt;!-- ELSE --&gt;
        ///        &lt;div class=&quot;info&quot;&gt;
        ///        &lt;!-- ENDIF --&gt;
        ///			&lt;h2&gt;{MEMBERS_TITLE}&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewgroupmemberlist_mobile {
            get {
                return ResourceManager.GetString("viewgroupmemberlist_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;!-- IF HAS_GROUPS --&gt;
        ///		&lt;div id=&quot;pane-profile-groups&quot; class=&quot;pane&quot;&gt;
        ///			&lt;h3&gt;{USER_DISPLAY_NAME_OWNERSHIP} Groups&lt;/h3&gt;
        ///			&lt;ul id=&quot;small-groups&quot;&gt;
        ///				&lt;!-- BEGIN groups_list --&gt;
        ///		&lt;li&gt;
        ///			&lt;a href=&quot;{groups_list.U_GROUP}&quot;&gt;
        ///				&lt;!-- IF groups_list.ICON --&gt;
        ///				&lt;img src=&quot;{groups_list.ICON}&quot; data-at2x=&quot;{groups_list.TILE}&quot; alt=&quot;{groups_list.TITLE}&quot; title=&quot;{groups_list.TITLE}&quot; /&gt;
        ///				&lt;!-- ELSE --&gt;
        ///				&lt;img src=&quot;/images/no_picture_100.png&quot; alt=&quot;{groups_list.TITLE}&quot; title=&quot;{groups_list.TITLE}&quot; /&gt;
        ///				&lt;!--  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewprofilegroups {
            get {
                return ResourceManager.GetString("viewprofilegroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- INCLUDE page_header.html --&gt;
        ///
        ///&lt;h2&gt;{SUBGROUP_TITLE}&lt;/h2&gt;
        ///
        ///&lt;!-- IF U_JOIN --&gt;
        ///&lt;p&gt;&lt;span id=&quot;join-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_JOIN}&quot;&gt;{L_JOIN_THIS_GROUP}&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///&lt;!-- IF U_LEAVE --&gt;
        ///&lt;p&gt;&lt;span id=&quot;leave-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_LEAVE}&quot;&gt;{L_LEAVE_THIS_GROUP}&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///&lt;!-- IF U_CANCEL --&gt;
        ///&lt;p&gt;&lt;span id=&quot;cancel-group&quot; class=&quot;post-button&quot;&gt;&lt;a href=&quot;{U_CANCEL}&quot;&gt;{L_CANCEL_MEMBERSHIP_REQUEST}&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;!-- ENDIF --&gt;
        ///
        ///&lt;!-- IF IS_WAITI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string viewsubgroup {
            get {
                return ResourceManager.GetString("viewsubgroup", resourceCulture);
            }
        }
    }
}
